### ISSUE TITLE
Startup Warning when creating language file

### ISSUE THREAD

**Issue by Whitescan** [Falyrion/AdvancedArmorStands#12]
Basically title...
```[14:09:28 INFO]: [AdvancedArmorStands] Enabling AdvancedArmorStands v1.19.0.0
[14:09:28 INFO]: [AdvancedArmorStands] Creating language file
[14:09:28 WARN]: [AdvancedArmorStands] Could not save lang.yml to plugins/AdvancedArmorStands/lang.yml because lang.yml already exists.```

I know it already exists because I configured it. No need to prompt the warning everytime.

**Comment by Falyrion** [comment]
> Basically title...
> 
> ```
> [14:09:28 INFO]: [AdvancedArmorStands] Creating language file
> [14:09:28 WARN]: [AdvancedArmorStands] Could not save lang.yml to plugins/AdvancedArmorStands/lang.yml because lang.yml already exists.```
> 
> I know it already exists because I configured it. No need to prompt the warning everytime.
> ```

Are you using the most recent version of the plugin? That issue happened years ago but should have been fixed for a long time.

The version should be displayed on the console and should be `1.19.0.0`.

**Comment by MajdT51** [comment]
Hi @Falyrion 

It happens on my server 2, not very critical tbh

[13:55:07 INFO]: [AdvancedArmorStands] Enabling AdvancedArmorStands v1.18.0.0
[13:55:07 INFO]: [AdvancedArmorStands] Creating language file
[13:55:07 WARN]: [AdvancedArmorStands] Could not save lang.yml to plugins/AdvancedArmorStands/lang.yml because lang.yml already exists.
[13:55:07 INFO]: [AdvancedArmorStands] Version v.1.18.0.0 (for bukkit 1.17+) enabled

**Comment by Whitescan** [comment]
It's still happening in version 1.19.0.0 and hasn't been fixed ever for me. Used this plugin all the way from 1.8.8 - 1.21.4
